(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: FP_Gen
 * File: FP_GenInit.st
 * Author: dominique
 * Created: November 21, 2011
 ********************************************************************
 * Implementation of program FP_Gen
 ********************************************************************)

PROGRAM _INIT

  // Envelope Bag Off/On 
  HMI_EnvB_bOnOffPB := gRecipeActive.bSelEnvBProd ;

END_PROGRAM

