(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A2_Cycle
 * File: A2_CycleInit.st
 * Author: Dominique
 * Created: October 15, 2011
 ********************************************************************
 * Implementation of program A2_Cycle
 ********************************************************************)

PROGRAM _INIT

  gstCycA[8].CycManTimSet.uiMasterParID := 428 ; // ParID 428 = CTRL Position controller: Input set position (in case real axis)

END_PROGRAM

