(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: Alarms1
 * File: NewProgramInit.st
 * Author: dominique
 * Created: December 09, 2011
 ********************************************************************
 * Implementation of program Alarms1
 ********************************************************************)

PROGRAM _INIT


  bTest := 0 ;
  Alarm1 := Alarm1 ; // D.M. RS26_Pyrollpack_14661 added just to be able to see all items at once in Monitor 

END_PROGRAM

