
TYPE
	MC_ACP_ENCOD_REF : 	STRUCT  (*structure with information about ACOPOS encoder*)
		Axis : UDINT; (*axis reference*)
		Slot : USINT; (*slot for the ACOPOS plug in module where the encoder is read (3 or 4)*)
	END_STRUCT;
	MC_ACP_ENCOD_PARAM_REF : 	STRUCT  (*structure with parameter for homing an external encoder*)
		HomingMode : USINT; (*choice of the homing mode*)
		ReadOffset : BOOL; (*choice if the home offset will be read*)
		Position : REAL; (*position after successful homing*)
		Offset : DINT; (*homing offset*)
	END_STRUCT;
	MC_ADVANCEDSHIFTPAR_REF : 	STRUCT  (*structure for using additional functions*)
		ShiftParID : UINT; (*ParID from which the offset shift is read*)
	END_STRUCT;
	MC_AUTDATA_TYP : 	STRUCT  (*structure for global cam automat parameters*)
		Master : UDINT; (*axis reference of the master*)
		StartPosition : REAL; (*start position of the master axis*)
		StartInterval : REAL; (*start interval of the master axis*)
		StartState : USINT; (*index for the start state*)
		StartMaRelPos : REAL; (*relative master start position in the cam profile*)
		MasterStartPosMode : USINT; (*mode for event type ncS_START*)
		MaxMasterVelocity : REAL; (*maximum speed of the master axis*)
		MasterParID : UINT; (*parameter ID of the master axis*)
		AddMasterParID : UINT; (*parameter ID of the additive master axis*)
		AddSlaveParID : UINT; (*parameter ID of the additive slave axis*)
		SlaveFactorParID : UINT; (*ParID for the multiplication factor of the slave axis*)
		EventParID : UINT; (*parameter ID for event input when event type is ncPAR_ID1*)
		EventParID2 : UINT; (*parameter ID for event input when event type is ncPAR_ID2*)
		EventParID3 : UINT; (*parameter ID for event input when event type is ncPAR_ID3*)
		EventParID4 : UINT; (*parameter ID for event input when event type is ncPAR_ID4*)
		SlaveLatchParID : UINT; (*ParID for the latch value of the slave axis when the compensation mode is ncSL_LATCHPOS*)
		State : ARRAY[0..14] OF MC_AUTDATA_STATE_TYP; (*for definition of basis state and 14 other states*)
	END_STRUCT;
	MC_AUTDATA_EVENT_TYP : 	STRUCT  (*structure for defining events for state transitions*)
		Type : USINT; (*event type*)
		Attribute : USINT; (*event attribute*)
		Action : UDINT; (*action at state transition*)
		NextState : USINT; (*index for next state*)
	END_STRUCT;
	MC_AUTDATA_STATE_TYP : 	STRUCT  (*structure for defining up to 15 cam automat states*)
		DisableStateInit : USINT; (*internal variable*)
		CamProfileIndex : UINT; (*index of camprofile used in state*)
		MasterFactor : UDINT; (*multiplication factor of the cam on the master axis*)
		SlaveFactor : DINT; (*multiplication factor of the cam on the slave axis*)
		CompMode : USINT; (*compansation mode*)
		MasterCompDistance : REAL; (*compensation distance of master axis*)
		SlaveCompDistance : REAL; (*compensation distance of slave axis*)
		RepeatCounterInit : UINT; (*start value state repeats for the ncCOUNT event*)
		RepeatCounterSet : UINT; (*counter state repeats for the ncCOUNT event*)
		MasterCamLeadIn : REAL; (*relative entry distance of master axis within the cam profile*)
		ExtendedCompLimits : UINT; (*extended compensation limits*)
		MinMasterCompDistance : REAL; (*minimum compensation distance for the master axis*)
		MinSlaveCompDistance : REAL; (*minimum compensation distance for the slave axis*)
		MaxSlaveCompDistance : REAL; (*maximum compensation distance for the slave axis*)
		MinSlaveCompVelocity : REAL; (*minimum speed of the slave axis in compensation*)
		MaxSlaveCompVelocity : REAL; (*maximum speed of the slave axis in compensation*)
		MaxSlaveAccelComp1 : REAL; (*maximum acceleration of the slave axis in compensation phase 1*)
		MaxSlaveAccelComp2 : REAL; (*maximum acceleration of the slave axis in compensation phase 2*)
		SlaveCompJoltTime : REAL; (*jolt time of the slave axis in the compensation*)
		MasterParID : UINT; (*Parameter ID of the master axis. 0 means global master ParID*)
		Event : ARRAY[0..4] OF MC_AUTDATA_EVENT_TYP; (*Definition of the event transition for the state*)
	END_STRUCT;
	MC_AUTINITOPTIONS_REF : 	STRUCT  (*structure with function block configuration*)
		GlobalParams : USINT; (*choose if global automat parameters should be transferred*)
		StateIndex : USINT; (*automat state index (0 to 14)*)
		EventIndex : USINT; (*automat event index (0 to 4)*)
		MaxStatesPerCycle : USINT; (*maximum number of states to be checked per task class cycle*)
		ParLock : USINT; (*lock for consistent online parameter change*)
		Force : BOOL; (*switch on or off force function*)
	END_STRUCT;
	MC_BR_EVINPUT_REF : 	STRUCT  (*structure with input information about trigger*)
		EventSourceParID : UINT; (*ACOPOS ParID as event source*)
		Edge : USINT; (*edge selection for the trigger event*)
	END_STRUCT;
	MC_BR_TRIGGER_REF : 	STRUCT  (*structure with information about event source*)
		EventSourceParID : UINT; (*ParID as event source*)
		ProbeParID : UINT; (*ParID whose value should be saved on the drive*)
		Edge : USINT; (*edge selection for the trigger event*)
		MinWidth : REAL; (*minimum trigger event width for the event to be considered valid*)
		MaxWidth : REAL; (*maximum trigger event width for the event to be considered valid*)
	END_STRUCT;
	MC_CALC_CAM_CONFIG_REF : 	STRUCT  (*structure for configuring additional options for the interpolation*)
		Mode : UINT; (*interpolation mode*)
		CamType : BOOL; (*cyclic or noncyclic cam*)
		NumberOfPolynomials : USINT; (*maximum number of polynomials being calculated*)
		MasterPeriod : DINT; (*master period*)
		StartSlope : REAL; (*start slope (velocity) of the cam*)
		StartCurvature : REAL; (*start curvature (acceleration) of the cam*)
		EndSlope : REAL; (*end slope (velocity) of the cam*)
		EndCurvature : REAL; (*end curvature (acceleration) of the cam*)
	END_STRUCT;
	MC_CAMPROFILE_TYP : 	STRUCT  (*structure with cam profile data*)
		MasterPeriod : DINT; (*length of the master period*)
		SlavePeriod : DINT; (*length of the slave period*)
		PolynomialNumber : UDINT; (*number of polynomials*)
		PolynomialData : ARRAY[0..63] OF MC_POLYNOMIAL_DATA; (*polynomial coefficient*)
	END_STRUCT;
	MC_CAMSWITCH_REF : 	STRUCT  (*structure with the reference to the switching actions*)
		TrackNumber : INT; (*reference to the track*)
		FirstOnPosition : ARRAY[0..15] OF REAL; (*lower boundary where the switch is ON*)
		LastOnPosition : ARRAY[0..15] OF REAL; (*upper boundary where the switch is ON*)
		Period : REAL; (*definition of the period*)
	END_STRUCT;
	MC_CAM_SECTION_TYP : 	STRUCT  (*structure with data for MC_CAM_SECTIONS_TYP*)
		MasterPosition : REAL; (*master side starting position of the section*)
		SlavePosition : REAL; (*slave side starting position of the section*)
		FirstDerivative : REAL; (*speed in the starting point of the sections*)
		SecondDerivative : REAL; (*acceleration in the starting point of the section*)
		Mode : USINT; (*specification of master and slave position absolute or relative to the previous point*)
		Type : UINT; (*motion rule*)
		InflectionPoint : REAL; (*master position of the inflection point*)
	END_STRUCT;
	MC_CAM_SECTIONS_TYP : 	STRUCT  (*structure with data for the cam sections*)
		Section : ARRAY[0..64] OF MC_CAM_SECTION_TYP; (*data of a point and the subsequent section*)
	END_STRUCT;
	MC_CYCLIC_POSITION : 	STRUCT  (*structure with the cyclic position data *)
		Integer : DINT;
		Real : REAL;
	END_STRUCT;
	MC_DATOBJ_REF : 	STRUCT  (*structure with parameter for saving the network trace data*)
		Name : STRING[32]; (*name of the data object or file*)
		Type : UINT; (*choose if data object or file*)
		Reserve : UINT; (*internal variable*)
		Device : STRING[32]; (*name of the file device*)
	END_STRUCT;
	MC_DRIVESTATUS_TYP : 	STRUCT  (*structure for the status information of the drive*)
		Simulation : BOOL; (*shows if the simulation mode is active*)
		NetworkInit : BOOL; (*shows if the network is initialized*)
		HomeSwitch : BOOL; (*shows if the digital reference switch input is active*)
		PosHWSwitch : BOOL; (*shows if the positive hardware end switch is active*)
		NegHWSwitch : BOOL; (*shows if the negative hardware end switch is active*)
		Trigger1 : BOOL; (*shows if the first trigger input is active*)
		Trigger2 : BOOL; (*shows if the second trigger input is active*)
		DriveEnable : BOOL; (*shows if the enable input is closed*)
		ControllerReady : BOOL; (*shows if the controller is ready to be turned on*)
		ControllerStatus : BOOL; (*shows if the controller is turned on*)
		HomingOk : BOOL; (*shows if the axis is referenced*)
		AxisError : BOOL; (*shows if at least one error or warning has occurred*)
		LagWarning : BOOL; (*shows if the lag error has exceeded the limit value specified for a warning*)
	END_STRUCT;
	MC_ENDLESS_POSITION : 	STRUCT  (*structure to save the endless position*)
		EndlessPositionData : ARRAY[0..1] OF MC_ENDLESS_POSITION_DATA;
	END_STRUCT;
	MC_ENDLESS_POSITION_DATA : 	STRUCT  (*structure to save the endless position*)
		MTPhase : DINT;
		MTDiffInteger : DINT;
		MTDiffFract : DINT;
		RefOffset : DINT;
		Checksum : UDINT;
	END_STRUCT;
	MC_ERRORRECORD_REF : 	STRUCT  (*structure with error messages that can occur after executing the command*)
		ParID : UINT; (*ParID at which the error occurred*)
		Number : UINT; (*error number*)
		Info : UDINT; (*additional information about the error number*)
	END_STRUCT;
	MC_ERRORTEXTCONFIG_REF : 	STRUCT  (*structure with function block configuration*)
		Format : UINT; (*format of the errortext*)
		LineLength : UINT; (*length of a line in the error text string*)
		DataLength : UINT; (*length of the error text string*)
		DataAddress : UDINT; (*address of the error text string*)
		DataObjectName : STRING[12]; (*name of the error text module*)
	END_STRUCT;
	MC_INPUT_REF : 	STRUCT  (*structure with reference to the input signal source*)
		Axis : UDINT; (*axis reference*)
		Slot : USINT; (*slot of the ACOPOS plug in module*)
		Channel : USINT; (*channel number of the input on the ACOPOS plug in module*)
	END_STRUCT;
	MC_NETTRACE_REF : 	STRUCT  (*structure with parameters for network command trace configuration*)
		Type : UDINT; (*trace type*)
		Reserve : UDINT; (*internal variable*)
	END_STRUCT;
	MC_NETTRACECONFIG_REF : 	STRUCT  (*structure with function block configuration*)
		DatObj : MC_DATOBJ_REF; (*parameters for saving the network trace data*)
		NetTrace : MC_NETTRACE_REF; (*parameters for network command trace configuration*)
	END_STRUCT;
	MC_OUTPUT_REF : 	STRUCT  (*structure with the reference to the signal output*)
		Axis : UDINT; (*axis reference*)
		Slot : USINT; (*slot of the ACOPOS plug-in module (2, 3, or 4)*)
		Channel : USINT; (*channel number of the output on the ACOPOS plug in module*)
	END_STRUCT;
	MC_PARTRACE_REF : 	STRUCT  (*structure with parameter for axis trace configuration*)
		Type : UDINT; (*trace type*)
		Reserve : UDINT; (*internal variable*)
		TracingTime : REAL; (*maximum trace recording length*)
		SamplingTime : REAL; (*sampling interval of the ParIDs*)
		Delay : REAL; (*trigger delay*)
		NetTriggerDelay : REAL; (*delay time of the trigger via the network*)
		Trigger : MC_TRACETRIGGER_REF; (*parameters for trigger event*)
		Parameter : ARRAY[0..29] OF MC_TRACEPARAM_REF; (*parameters to record*)
	END_STRUCT;
	MC_PARTRACECONFIG_REF : 	STRUCT  (*structure with function block configuration*)
		DatObj : MC_DATOBJ_REF; (*parameters for saving the network trace data*)
		ParTrace : MC_PARTRACE_REF; (*parameters for axis trace configuration*)
	END_STRUCT;
	MC_POLYNOMIAL_DATA : 	STRUCT  (*structure with polynomial coefficient*)
		a : REAL;
		b : REAL;
		c : REAL;
		d : REAL;
		e : REAL;
		f : REAL;
		g : REAL;
		x : REAL; (*master end position of the polynomial*)
		Reserve : UDINT; (*internal variable*)
	END_STRUCT;
	MC_POWERDATA_REF : 	STRUCT  (*structure for the determined datas of the powermeter function*)
		IntervalNumber : UDINT; (*number of evaluated intervals*)
		IntervalDuration : DINT; (*ItervalTime of the last interval*)
		AverageActivePower : REAL; (*average effective Power*)
		AverageReactivePower : REAL; (*average idle Power*)
		MaximumActivePower : REAL; (*maximum effective Power*)
		MinimalActivePower : REAL; (*minimum effective Power*)
		ConsumedEnergy : REAL; (*used energy*)
		RegeneratedEnergy : REAL; (*produced energy*)
		EnergyBalance : REAL; (*spread between used and produced energy*)
		Reserve1 : REAL; (*reserve variable*)
		Reserve2 : REAL; (*reserve variable*)
		Reserve3 : REAL; (*reserve variable*)
		Reserve4 : REAL; (*reserve variable*)
		Reserve5 : REAL; (*reserve variable*)
	END_STRUCT;
	MC_RECORD_INFO_REF : 	STRUCT  (*structure for cyclic read data info *)
		Record : ARRAY[0..7] OF MC_RECORD_REF;
	END_STRUCT;
	MC_RECORD_REF : 	STRUCT  (*structure for cyclic read data info*)
		Size : UINT;
		Reserve1 : UINT; (*alignment*)
		OneByteCount : USINT;
		TwoByteCount : USINT;
		FourByteCount : USINT;
		Reserve2 : USINT; (*alignment*)
		ParID : ARRAY[0..5] OF UINT;
		Reserve3 : ARRAY[0..3] OF UINT; (*internal variable*)
	END_STRUCT;
	MC_SETUP_CONTROLLER_CFG_REF : 	STRUCT  (*structure with the configuration parameters*)
		DatObj : MC_DATOBJ_REF; (*parameters for saving the setup datas*)
		SetupControllerPar : MC_SETUP_CONTROLLER_PAR_REF; (*parameters for executing the controllersetup*)
	END_STRUCT;
	MC_SETUP_CONTROLLER_PAR_REF : 	STRUCT  (*structure with parameters for the setup*)
		Mode : UINT; (*mode for the controllersetup*)
		MaxCurrentPercent : REAL; (*percentage of the rated current which is used durring Setup [%]*)
		MaxSpeedPercent : REAL; (*maximum speed of the movement in reference to the limits [%]*)
		MaxDistance : REAL; (*maximum distance which is moved durring the setup*)
		MaxLagError : REAL; (*maximum lag error which can occure durring the setup*)
	END_STRUCT;
	MC_SETUP_IND_MOTOR_CFG_REF : 	STRUCT  (*structure with the configuration parameters*)
		DatObj : MC_DATOBJ_REF; (*parameters for saving the setup datas*)
		SetupInductionMotorPar : MC_SETUP_IND_MOTOR_PAR_REF; (*parameters for executing the motorsetup*)
	END_STRUCT;
	MC_SETUP_IND_MOTOR_PAR_OPT_REF : 	STRUCT  (*this parameters are only transered if they are not 0*)
		PolePairs : USINT; (*numbers of polepairs*)
		VoltageConstant : REAL; (*voltage constant [mVmin]*)
		MaxSpeed : REAL; (*maximal numbers of revolutions [1/min]*)
		StallTorque : REAL; (*standstill torque [Nm]*)
		RatedTorque : REAL; (*rated torque [Nm]*)
		PeakTorque : REAL; (*maximum torque [Nm]*)
		TorqueConstant : REAL; (*torque constant [Nm/A]*)
		StallCurrent : REAL; (*standstill current [A]*)
		PeakCurrent : REAL; (*maximum current [A]*)
		MagnetizingCurrent : REAL; (*magnetizing current [A]*)
	END_STRUCT;
	MC_SETUP_IND_MOTOR_PAR_REF : 	STRUCT  (*structure with parameters for the setup*)
		Mode : UINT; (*mode of the motor setup*)
		RatedVoltage : REAL; (*rated voltage [V]*)
		RatedCurrent : REAL; (*rated current [A]*)
		RatedSpeed : REAL; (*rated numbers of revolutions [1/min]*)
		RatedFrequency : REAL; (*rated frequenzy [Hz]*)
		PowerFactor : REAL; (*cos phi*)
		OptionalData : MC_SETUP_IND_MOTOR_PAR_OPT_REF; (*optional parameters for the motorsetup*)
	END_STRUCT;
	MC_SETUP_ISQ_RIPPLE_CFG_REF : 	STRUCT  (*structure with the configuration parameters*)
		DatObj : MC_DATOBJ_REF; (*parameters for saving the setup data*)
		SetupIsqRipplePar : MC_SETUP_ISQ_RIPPLE_PAR_REF; (*structure with the parameters for the setup*)
	END_STRUCT;
	MC_SETUP_ISQ_RIPPLE_PAR_REF : 	STRUCT  (*structure with parameters for the setup*)
		Mode : UINT;
		RefSystem : UINT;
		PositionOffset : REAL;
		Velocity : REAL;
	END_STRUCT;
	MC_SETUP_MOTOR_PHA_CFG_REF : 	STRUCT  (*structure with configuration parameters*)
		DatObj : MC_DATOBJ_REF; (*parmeters for saving the setup data*)
		SetupMotorPhasingPar : MC_SETUP_MOTOR_PHA_PAR_REF; (*parmeters for executing the phasing setup*)
	END_STRUCT;
	MC_SETUP_MOTOR_PHA_PAR_REF : 	STRUCT  (*structure with parameters for the setup*)
		Mode : UINT; (*mode for the phasing setup*)
		Current : REAL; (*phasing current [A]*)
		Time : REAL; (*phasing time [s]*)
	END_STRUCT;
	MC_SETUP_OUTPUT_REF : 	STRUCT  (*structure where the output datas are written on*)
		Quality : REAL; (*quality  of the executed setup*)
		DataObjectIdent : UDINT; (*ident of the saved data object*)
	END_STRUCT;
	MC_SETUP_PHASING_RESULT_REF : 	STRUCT  (*structure with result data of phasing setup*)
		PolePairs : USINT; (*pole pairs*)
		CommutationOffset : REAL; (*commutation offset [rad]*)
	END_STRUCT;
	MC_TRACETRIGGER_REF : 	STRUCT  (*structure with parameter for trigger events*)
		Axis : UDINT; (*axis reference*)
		ParID : UINT; (*trigger source ParID*)
		Event : USINT; (*trigger event*)
		Reserve : USINT; (*internal variable*)
		Threshold : REAL; (*threshold value*)
		Window : REAL; (*window around the threshold value*)
	END_STRUCT;
	MC_TRACEPARAM_REF : 	STRUCT  (*structure with parameter to record*)
		Axis : UDINT; (*axis reference*)
		ParID : UINT; (*ParID to record*)
		Reserve : UINT; (*internal variable*)
	END_STRUCT;
	MC_TRACK_REF : 	STRUCT  (*structure with the reference track related properties*)
		OnCompensation : TIME; (*compensation time with which the switching on is advanced in time*)
		OffCompensation : TIME; (*compensation time with which the switching off is advanced in time*)
		Hysteresis : REAL; (*distance from the switching point*)
	END_STRUCT;
	MC_TRIGGER_REF : 	STRUCT  (*structure with data of trigger input signal source*)
		InputSource : USINT; (*source of the trigger event*)
		Edge : USINT; (*select the rising or the trailing edge of the trigger signal*)
		PosSource : USINT; (*select the position to be latched ncS_SET / ncS_ACT*)
		TouchProbeID : USINT; (*instance number of the touchprobe function on the selected drive (1 - 8)*)
	END_STRUCT;
	MC_0068_IS_TYP : 	STRUCT  (*internal structure for MC_BR_HomeAcpEncoder*)
		C_Execute : BOOL; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		LockID : USINT; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_EncoderOffset : DINT; (*internal variable*)
		C_HomingMode : USINT; (*internal variable*)
		C_HomingModeBits : USINT; (*internal variable*)
		C_ReadOffset : BOOL; (*internal variable*)
		C_Slot : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		C_Position : DINT; (*internal variable*)
		C_Offset : DINT; (*internal variable*)
		BitIndex : UINT; (*internal variable*)
		HomingStatusOffset : UINT; (*internal variable*)
		HomingStatusRecIndex : USINT; (*internal variable*)
		FbID : USINT; (*internal variable*)
	END_STRUCT;
	MC_0069_IS_TYP : 	STRUCT  (*internal structure for MC_BR_CyclicRead *)
		C_Valid : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ParID : UINT; (*internal variable*)
		C_DataAddress : UDINT; (*internal variable*)
		C_DataType : UINT; (*internal variable*)
		C_Mode : UINT; (*internal variable*)
		Offset : UINT; (*internal variable*)
		RecIndex : USINT; (*internal variable*)
		ParIndex : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
	END_STRUCT;
	MC_0070_IS_TYP : 	STRUCT  (*internal structure for MC_BR_CyclicWrite*)
		C_Valid : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ParID : UINT; (*internal variable*)
		C_DataAddress : UDINT; (*internal variable*)
		C_DataType : UINT; (*internal variable*)
		C_Mode : UINT; (*internal variable*)
		ParIndex : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
		DataLength : USINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		Reserve : UINT; (*internal variable*)
	END_STRUCT;
	MC_0071_IS_TYP : 	STRUCT  (*internal structure for MC_BR_Simulation*)
		C_Execute : BOOL; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		state : USINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		C_SimulationCommand : UINT; (*internal variable*)
	END_STRUCT;
	MC_0076_IS_TYP : 	STRUCT  (*internal structure for MC_BR_InitAutData*)
		C_Execute : BOOL; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_GlobalParams : USINT; (*internal variable*)
		C_StateIndex : USINT; (*internal variable*)
		C_EventIndex : USINT; (*internal variable*)
		C_MaxStatesPerCycle : USINT; (*internal variable*)
		C_ParLock : USINT; (*internal variable*)
		C_AutData : MC_AUTDATA_TYP; (*internal variable*)
		LockIDMa : USINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		C_Force : USINT; (*internal variable*)
		readSlot : USINT; (*internal variable*)
		sendSlot : USINT; (*internal variable*)
		paramCount : UINT; (*internal variable*)
		lockActive : BOOL; (*internal variable*)
		actStatesInCycle : USINT; (*internal variable*)
		stateCount : USINT; (*internal variable*)
		eventCount : USINT; (*internal variable*)
		stateParInImg : USINT; (*internal variable*)
		resetStates : BOOL; (*internal variable*)
		setStateIndex : BOOL; (*internal variable*)
		lastState : USINT; (*internal variable*)
		nextState : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
		LockIDSend : USINT; (*internal variable*)
		Reserve1 : USINT; (*internal variable*)
		Reserve2 : UINT; (*internal variable*)
	END_STRUCT;
	MC_0077_IS_TYP : 	STRUCT  (*internal structure for MC_BR_GetErrorText*)
		C_Execute : BOOL; (*internal variable*)
		LockID : USINT; (*internal variable*)
		C_ErrorRecord : MC_ERRORRECORD_REF; (*internal variable*)
		C_Configuration : MC_ERRORTEXTCONFIG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0078_IS_TYP : 	STRUCT  (*internal structure for MC_BR_NetTrace*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_Configuration : MC_NETTRACECONFIG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ErrorRecord : MC_ERRORRECORD_REF; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0080_IS_TYP : 	STRUCT  (*internal structure for MC_BR_ParTrace*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_Configuration : MC_PARTRACECONFIG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ErrorRecord : MC_ERRORRECORD_REF; (*internal variable*)
		StartSaveStarted : BOOL; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0081_IS_TYP : 	STRUCT  (*internal structure for MC_BR_MoveCyclicPosition*)
		C_CyclicPosition : MC_CYCLIC_POSITION; (*internal variable*)
		C_Velocity : REAL; (*internal variable*)
		C_Acceleration : REAL; (*internal variable*)
		C_Deceleration : REAL; (*internal variable*)
		C_PositionParID : UINT; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_Valid : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ReceiveParID : UINT; (*internal variable*)
		readSlot : UINT; (*internal variable*)
		Reserve1 : UDINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		MoveID : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0082_IS_TYP : 	STRUCT  (*internal structure for MC_BR_ReadCyclicPosition*)
		C_ParID : UINT; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_Valid : BOOL; (*internal variable*)
		C_CyclicPosition : MC_CYCLIC_POSITION; (*internal variable*)
		C_Offset : DINT; (*internal variable*)
		sendSlot : UINT; (*internal variable*)
		MnPResParIndex : UINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0083_IS_TYP : 	STRUCT  (*internal structure for MC_BR_GetCamSlavePosition*)
		C_Execute : BOOL; (*internal variable*)
		C_DataAddress : UDINT; (*internal variable*)
		C_MasterPosition : REAL; (*internal variable*)
		C_MasterFactor : UDINT; (*internal variable*)
		C_SlaveFactor : DINT; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_SlavePosition : REAL; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0084_IS_TYP : 	STRUCT  (*internal structure for MC_BR_GetCamMasterPosition*)
		C_Execute : BOOL; (*internal variable*)
		C_DataAddress : UDINT; (*internal variable*)
		C_MasterStartPosition : REAL; (*internal variable*)
		C_SlavePosition : REAL; (*internal variable*)
		C_MasterFactor : UDINT; (*internal variable*)
		C_SlaveFactor : DINT; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_MasterPosition : REAL; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0088_IS_TYP : 	STRUCT  (*internal structure for MC_BR_SetupInductionMotor*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_Configuration : MC_SETUP_IND_MOTOR_CFG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_SetupOutput : MC_SETUP_OUTPUT_REF; (*internal Variable*)
		LockIDPar : USINT; (*internal variable*)
		Reserve : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0089_IS_TYP : 	STRUCT  (*internal structure for MC_BR_PowerMeter*)
		C_Mode : USINT; (*internal variable*)
		C_IntervalTime : UINT; (*internal variable*)
		C_RestartInterval : BOOL; (*internal variable*)
		C_EventInput : MC_BR_EVINPUT_REF; (*internal variable*)
		C_Valid : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		CC_ErrorID : UINT; (*internal variable*)
		C_PowerData : MC_POWERDATA_REF; (*internal variable*)
		C_MissedIntervals : UINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		IntervalDurationOffset : UINT; (*internal variable*)
		IntervalDurationRecIndex : USINT; (*internal variable*)
		AverageActivePowerOffset : UINT; (*internal variable*)
		AverageActivePowerRecIndex : USINT; (*internal variable*)
		AverageReactivePowerOffset : UINT; (*internal variable*)
		AverageReactivePowerRecIndex : USINT; (*internal variable*)
		MaximumActivePowerOffset : UINT; (*internal variable*)
		MaximumActivePowerRecIndex : USINT; (*internal variable*)
		MinimalActivePowerOffset : UINT; (*internal variable*)
		MinimalActivePowerRecIndex : USINT; (*internal variable*)
		ConsumedEnergyOffset : UINT; (*internal variable*)
		ConsumedEnergyRecIndex : USINT; (*internal variable*)
		RegEnergyOffset : UINT; (*internal variable*)
		RegEnergyRecIndex : USINT; (*internal variable*)
		LockIDPmet : USINT; (*internal variable*)
		CDLockID : USINT; (*internal variable*)
		Reserve1 : UINT; (*internal variable*)
		Reserve2 : UINT; (*internal variable*)
		IntervalTimeMin : DINT; (*internal variable*)
		ParamCnt : USINT; (*Internal variable*)
		CountCnt : USINT; (*internal variable*)
		CountOffset : ARRAY[0..7] OF UINT; (*internal variable*)
		CountRecIndex : ARRAY[0..7] OF USINT; (*internal variable*)
		saveParamCnt : USINT; (*internal variable*)
		firstFreeParam : USINT; (*internal variable*)
		lastFreeParam : USINT; (*internal variable*)
		dataConfigDone : BOOL; (*internal variable*)
		SptID : USINT; (*internal variable*)
		VarIndex : UINT; (*internal variable*)
		CompIndex : UINT; (*internal variable*)
		NextState : USINT; (*internal variable*)
		ReserveOffset01 : UINT; (*internal variable*)
		ReserveRecIndex01 : USINT; (*internal variable*)
		ReserveOffset02 : UINT; (*internal variable*)
		ReserveRecIndex02 : USINT; (*internal variable*)
		ReserveOffset03 : UINT; (*internal variable*)
		ReserveRecIndex03 : USINT; (*internal variable*)
		ReserveOffset04 : UINT; (*internal variable*)
		ReserveRecIndex04 : USINT; (*internal variable*)
		ReserveOffset05 : UINT; (*internal variable*)
		ReserveRecIndex05 : USINT; (*internal variable*)
		Reserve3 : UDINT; (*internal variable*)
		Reserve4 : UDINT; (*internal variable*)
		CyclicDataTaskClassCycleTime : UDINT; (*internal variable*)
		Reserve5 : USINT; (*internal variable*)
		Reserve6 : UINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0090_IS_TYP : 	STRUCT  (*internal structure for MC_BR_SetupController*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_Configuration : MC_SETUP_CONTROLLER_CFG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_SetupOutput : MC_SETUP_OUTPUT_REF; (*internal Variable*)
		LockIDPar : USINT; (*internal variable*)
		Reserve : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0092_IS_TYP : 	STRUCT  (*internal structure for MC_BR_MoveCyclicVelocity*)
		C_CyclicVelocity : REAL; (*internal variable*)
		C_Direction : USINT; (*internal variable*)
		C_Acceleration : REAL; (*internal variable*)
		C_Deceleration : REAL; (*internal variable*)
		C_VelocityParID : UINT; (*internal variable*)
		C_Valid : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ReceiveParID : UINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		MoveID : USINT; (*internal variable*)
		VarIndex : UINT; (*internal variable*)
		SptID : USINT; (*internal variable*)
		readSlot : UINT; (*internal variable*)
		Reserve1 : UDINT; (*internal variable*)
		ArithIndex : UINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0093_IS_TYP : 	STRUCT  (*internal structure for MC_BR_CalcCamFromPoints*)
		C_Configuration : MC_CALC_CAM_CONFIG_REF; (*internal variable*)
		state : USINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
	END_STRUCT;
	MC_0095_IS_TYP : 	STRUCT  (*Internal structure for MC_BR_VelocityControl*)
		Enable : BOOL; (*internal variable*)
		Reserve1 : USINT; (*alignment*)
		Reserve2 : USINT; (*alignment*)
		Reserve3 : USINT; (*alignment*)
		CyclicVelocity : REAL; (*internal variable*)
		CyclicVelocityCorrection : REAL; (*internal variable*)
		CyclicVelCorrPerRev : REAL; (*internal variable*)
		CyclicTorque : REAL; (*internal variable*)
		TorqueMode : USINT; (*internal variable*)
		Reserve4 : USINT; (*alignment*)
		Reserve5 : USINT; (*alignment*)
		Reserve6 : USINT; (*alignment*)
		Acceleration : REAL; (*internal variable*)
		Deceleration : REAL; (*internal variable*)
		SctrlKv : REAL; (*internal variable*)
		SctrlTn : REAL; (*internal variable*)
		InitSctrl : BOOL; (*internal variable*)
		Active : BOOL; (*internal variable*)
		Busy : BOOL; (*internal variable*)
		CommandAborted : BOOL; (*internal variable*)
		Error : BOOL; (*internal variable*)
		Reserve : USINT; (*alignment*)
		ErrorID : UINT; (*internal variable*)
		SctrlInitialized : BOOL; (*internal variable*)
		DisableFBactive : BOOL; (*internal variable*)
		state : UINT; (*internal variable*)
		LastState : UINT; (*internal variable*)
		NextState : UINT; (*internal variable*)
		VarID : UINT; (*internal variable*)
		SptID : USINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		MoveID : USINT; (*internal variable*)
		LockIDFb : USINT; (*internal variable*)
		CyclicVelParIndex : USINT; (*internal variable*)
		CyclicVelCorrParIndex : USINT; (*internal variable*)
		CyclicTorqueParIndex : USINT; (*internal variable*)
		Reserve7 : USINT; (*alignment*)
		Reserve8 : USINT; (*alignment*)
		InitValue_SctrlKv : REAL; (*internal variable*)
		InitValue_SctrlTn : REAL; (*internal variable*)
		InitValue_tpredict : REAL; (*internal variable*)
		InitValue_S_ACT_PARID : UINT; (*internal variable*)
		Reserve9 : USINT; (*alignment*)
		Reserve12 : USINT; (*alignment*)
		C_ErrorID : UINT; (*internal variable*)
		Reserve10 : USINT; (*alignment*)
		Reserve11 : USINT; (*alignment*)
	END_STRUCT;
	MC_0097_IS_TYP : 	STRUCT  (*internal structure for MC_BR_SetupMotorPhasing*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_Configuration : MC_SETUP_MOTOR_PHA_CFG_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_CommandAborted : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_SetupOutput : MC_SETUP_OUTPUT_REF; (*internal variable*)
		C_SetupResult : MC_SETUP_PHASING_RESULT_REF; (*internal variable*)
		Reserve1 : UDINT; (*internal variable*)
		Reserve2 : UDINT; (*internal variable*)
		Reserve3 : UDINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	MC_0098_IS_TYP : 	STRUCT  (*internal structure for MC_BR_CyclicReadDataInfo*)
		Valid : BOOL; (*internal variable*)
		Busy : BOOL; (*internal variable*)
		Error : BOOL; (*internal variable*)
		tkNo : SINT; (*internal variable*)
		ErrorID : UINT; (*internal variable*)
		state : UINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		Reserve1 : USINT; (*alignment*)
		Reserve2 : UINT; (*alignment*)
		cycleTime : UDINT; (*internal variable*)
	END_STRUCT;
	MC_0099_IS_TYP : 	STRUCT  (*internal structure for MC_BR_AutomatCommand*)
		Enable : BOOL; (*internal variable*)
		Start : BOOL; (*internal variable*)
		Stop : BOOL; (*internal variable*)
		Restart : BOOL; (*internal variable*)
		Deceleration : REAL; (*internal variable*)
		EndAutomat : BOOL; (*internal variable*)
		SetSignal1 : BOOL; (*internal variable*)
		SetSignal2 : BOOL; (*internal variable*)
		SetSignal3 : BOOL; (*internal variable*)
		SetSignal4 : BOOL; (*internal variable *)
		ResetSignal1 : BOOL; (*internal variable*)
		ResetSignal2 : BOOL; (*internal variable*)
		ResetSignal3 : BOOL; (*internal variable*)
		ResetSignal4 : BOOL; (*internal variable*)
		TransferParLock : BOOL; (*internal variable*)
		SelectParLock : USINT; (*internal variable*)
		Active : BOOL; (*internal variable*)
		Busy : BOOL; (*internal variable*)
		CommandAborted : BOOL; (*internal variable*)
		Error : BOOL; (*internal variable*)
		Running : BOOL; (*internal variable*)
		ErrorID : UINT; (*internal variable*)
		StandBy : BOOL; (*internal variable*)
		ParLockTransferred : BOOL; (*internal variable*)
		ActualStateIndex : USINT; (*internal variable*)
		InCam : BOOL; (*internal variable*)
		ActualStateCamIndex : UINT; (*internal variable*)
		InCompensation : BOOL; (*internal variable*)
		state : USINT; (*internal variable*)
		cmdStart : BOOL; (*internal variable*)
		cmdStop : BOOL; (*internal variable*)
		cmdSetSignal : ARRAY[0..3] OF BOOL; (*internal variable*)
		cmdResetSignal : ARRAY[0..3] OF BOOL; (*internal variable*)
		cmdRestart : BOOL; (*internal variable*)
		cmdEndAutomat : BOOL; (*internal variable*)
		cmdParLock : BOOL; (*internal variable*)
		SptID : USINT; (*internal variable*)
		BitIndex : UINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		LockID : USINT; (*internal variable*)
		BitValue : UDINT; (*internal variable*)
		BitValueOffset : UINT; (*internal variable*)
		BitValueRecIndex : USINT; (*internal variable*)
		StateDataIdxRecIndex : USINT; (*internal variable*)
		StateDataIdxOffset : UINT; (*internal variable*)
		SignalSet : USINT; (*internal variable*)
		SignalReset : USINT; (*internal variable*)
		ParLockPending : BOOL; (*internal variable*)
		AutStatus : USINT; (*internal varibale*)
		AutActCamType : USINT; (*internal variable*)
		MoveID : USINT; (*internal variable*)
		ChangeAxisState : BOOL; (*internal variable*)
		expectRunning : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
	END_STRUCT;
	MC_0101_IS_TYP : 	STRUCT  (*internal structure for MC_BR_SetupIsqRipple*)
		Execute : BOOL; (*internal variable*)
		Done : BOOL; (*internal variable*)
		Command : UINT; (*internal variable*)
		Configuration : MC_SETUP_ISQ_RIPPLE_CFG_REF; (*internal variable*)
		Busy : BOOL; (*internal variable*)
		CommandAborted : BOOL; (*internal variable*)
		Error : BOOL; (*internal variable*)
		state : USINT; (*internal variable*)
		ErrorID : UINT; (*internal variable*)
		LockIDPar : USINT; (*internal variable*)
		SetupOutput : MC_SETUP_OUTPUT_REF; (*internal variable*)
	END_STRUCT;
	MC_0102_IS_TYP:     STRUCT  (*internal structure for MC_BR_ParTraceConfig*)
		C_Execute : BOOL; (*internal variable*)
		C_Command : UINT; (*internal variable*)
		C_AdrTraceConfig : UDINT; (*internal variable*)
		C_TraceConfig : MC_PARTRACE_REF; (*internal variable*)
		C_DataObject : MC_DATOBJ_REF; (*internal variable*)
		C_Done : BOOL; (*internal variable*)
		C_Busy : BOOL; (*internal variable*)
		C_Error : BOOL; (*internal variable*)
		C_ErrorID : UINT; (*internal variable*)
		C_ErrorRecord : MC_ERRORRECORD_REF; (*internal variable*)
		state : USINT; (*internal variable*)
	END_STRUCT;
	    
END_TYPE
