(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A1_CamProfCalc
 * File: A1_CamProfCalcInit.st
 * Author: dominique
 * Created: August 24, 2011
 ********************************************************************
 * Implementation of program A1_CamProfCalc
 ********************************************************************)

PROGRAM _INIT
  // Came profile Perf index
  g_uiIndexCamProfPerf := 1 ;
  

END_PROGRAM

