(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A12_Cycle
 * File: A12_CycleInit.st
 * Author: dominique
 * Created: November 21, 2011
 ********************************************************************
 * Implementation of program A12_Cycle
 ********************************************************************)

PROGRAM _INIT

  gstCycA[12].CycManTimSet.uiMasterParID := 428 ; // ParID 428 = CTRL Position controller: Input set position (in case real axis)

END_PROGRAM

