(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A15_MotionCycle
 * File: A15_MotionCycleInit.st
 * Author: dominique
 * Created: November 06, 2011
 ********************************************************************
 * Implementation of program A15_MotionCycle
 ********************************************************************)

PROGRAM _INIT


  rTest := 0 ;


END_PROGRAM

