(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A7_Cycle
 * File: A7_CycleInit.st
 * Author: dominique
 * Created: August 01, 2011
 ********************************************************************
 * Implementation of program A7_Cycle
 ********************************************************************)

PROGRAM _INIT

  gstCycA[7].CycManTimSet.uiMasterParID := 428 ; // ParID 428 = CTRL Position controller: Input set position (in case real axis)

END_PROGRAM

