(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: Revision
 * File: RevisionCyclic.st
 * Author: pkiel
 * Created: December 14, 2009
 ********************************************************************
 * Implementation of program Revision
 ********************************************************************)

PROGRAM _CYCLIC

	CurrentSoftwareRevision := 1.1;

END_PROGRAM
