(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: Test_Simul
 * File: Test_SimulInit.st
 * Author: dominique
 * Created: August 20, 2011
 ********************************************************************
 * Implementation of program Test_Simul
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

