(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A5_Draw
 * File: A5_DrawInit.st
 * Author: dominique
 * Created: January 06, 2012
 ********************************************************************
 * Implementation of program NewProgram
 ********************************************************************)

PROGRAM _INIT


    HMI_rEntry_Draw_Set := gRecipeActive.Entry_Draw ;


END_PROGRAM

