(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A13_Cycle
 * File: A13_CycleInit.st
 * Author: dominique
 * Created: November 21, 2011
 ********************************************************************
 * Implementation of program A13_Cycle
 ********************************************************************)

PROGRAM _INIT

  gstCycA[13].CycManTimSet.uiMasterParID := 428 ; // ParID 428 = CTRL Position controller: Input set position (in case real axis)

END_PROGRAM

