(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A1_Cycle
 * File: A1_CycleInit.st
 * Author: dominique
 * Created: August 01, 2011
 ********************************************************************
 * Implementation of program A1_Cycle
 ********************************************************************)

PROGRAM _INIT


(* TODO : Add your code here *)


END_PROGRAM

