(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: Units
 * File: NewProgramInit.st
 * Author: dominique
 * Created: December 09, 2011
 ********************************************************************
 * Implementation of program Units
 ********************************************************************)

PROGRAM _INIT


  InchMetric_PB := 0 ; // Inch as default value

END_PROGRAM

