(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: A1_Cycle
 * File: A1_CycleInit.st
 * Author: dominique
 * Created: August 01, 2011
 ********************************************************************
 * Implementation of program A1_Cycle
 ********************************************************************)

PROGRAM _INIT

  gstCycA[4].CycManTimSet.uiMasterParID := 428 ; // ParID 428 = CTRL Position controller: Input set position (in case real axis)

END_PROGRAM

