(********************************************************************
 * COPYRIGHT -- .
 ********************************************************************
 * Program: SetSpeedMode
 * File: SetSpeedModeInit.st
 * Author: dominique
 * Created: September 29, 2011
 ********************************************************************
 * Implementation of program SetSpeedMode
 ********************************************************************)

PROGRAM _INIT
  HMI_uiConfirmSetSpeedVisibl := 1 ;
END_PROGRAM

